### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by Janaza** [Janaza/D7024E#37]
Suggested:
RPC senders (primitive)-> rpc.go 
Listener() & handler funcs -> network.go
FindNode (iterative)-> findnode.go
FindValue (iterative)-> findvalue.go
store (iterative)-> store.go
cli() -> cli.go

Change all RPC senders to take *Kademlia as receiver instead of *Network, remove *Kademlia from network struct. All listeners and handlers still takes network as receiver.

**Comment by Hampusholmstrom** [comment]
cli() -> cli.go done. See GT-56.

**Comment by Hampusholmstrom** [comment]
SendPing should only take network struct

**Comment by Janaza** [comment]
Expanding on comment from @Hampusholmstrom. 
With SendPingMsg() we instead send e.g. "ping nodeid ip:port" then go back to Listener() and letting Listener() handle the pong response calling a new function HandlePongMsg(). 
A new function SendPongMsg() will be called from the reciver of the ping sending pong to ip:port.

This avoids awaiting a pong response after sending ping in SendPingMsg() and avoids using connection.Read().

tl.dr: Implement SendPongMsg(), HandlePongMsg() avoid using connection.Read(). 
IF "ping": send pong and add contact. 
IF "pong": add contact.

**Comment by Janaza** [comment]
Updated comment ^
