### ISSUE TITLE
PUT/STORE translates input to kad.-id before or after hashing.

### ISSUE THREAD

**Issue by Janaza** [Janaza/D7024E#54]
Entering e.g. 123 as value in put hashes 123 as cba3802d0d10dd128a8e065c2a48a78d94ed40ab however 123 should be hashed as 40bd001563085fc35165329ea1ff5c5ecbdbbeef (in SHA-1).
Might be that the value gets double hashed, hashed and then translated to a kademlia-ID or something similar.

**Comment by Hampusholmstrom** [comment]
Found a small bug in msgHandle.
For store messages, HandleStoreMsg(msg[5:], resp) means it sends a whitespace before the msg. When we PUT "123" it actually stores hash of " 123".

SHA-1 hash for " 123" = CBA3802D0D10DD128A8E065C2A48A78D94ED40AB
SHA-1 hash for "123" = 40BD001563085FC35165329EA1FF5C5ECBDBBEEF

Resolved in GT-56.
