### ISSUE TITLE
Add better handling of cli

### ISSUE THREAD

**Issue by Janaza** [Janaza/D7024E#56]
Entering too short CLI commands causes a crash i.e. most commands take text[:3] or more, entering a command where len(text) < 3 causes slice out of bounds. Add error escaping or use something like strings.Contains("command", text).

**Comment by Hampusholmstrom** [comment]
CLI moved to separate file outside of main package. 

No crashes anymore but do not get any error message when CLI is wrong.

**Comment by Hampusholmstrom** [comment]
Also fixed store msghandler to hash msg right.  see GT-54.
